[package]
name = "ocpp"
version = "0.2.0"
edition = "2021"
repository = "https://bitbucket.org/mastercomms/ocpp"
authors = [ "Mastercom <software@mastercom.com.au>", "Cameron Duff <cameron.duff@mastercom.com.au>", "Lewis Hyman <lewis.hyman@mastercom.com.au>" ]

[dependencies]
tracing = "^0.1"
serde_with = "^1.0"
serde_json = "^1.0"
lazy_static = "^1.4"
strum_macros = "^0.23"
serde = { version = "^1.0", features = [ "derive" ] }
chrono = { version = "^0.4", features = [ "serde" ] }
jsonschema = { version = "^0.15", default-features = false }

ocpp_json_validate = { version = "^1.0", path = "./ocpp_json_validate" }
