[package]
name = "ocpp"
version = "0.1.0"
edition = "2021"
repository = "https://bitbucket.org/mastercomms/ocpp"

[dependencies]
serde_json = "^1.0"
serde = { version = "^1.0", features = [ "derive" ] }
chrono = { version = "^0.4", features = [ "serde" ] }
jsonschema = { version = "^0.14", default-features = false }
lazy_static = "1.4.0"
thiserror = "1.0.30"
serde_with = "^1"
tracing = "^0.1"
strum_macros = "^0.23"


ocpp_json_validate = { version = "^1.0", path = "./ocpp_json_validate" }
