[package]
name = "ocpp"
version = "0.1.0"
edition = "2018"
repository = "https://bitbucket.org/mastercomms/ocpp"

[dependencies]
serde_json = "^1.0"
serde = { version = "^1.0", features = ["derive"] }
jsonschema = "^0.12.1"
chrono = { version = "^0.4", features = ["serde"] }

