chain_width                   = 130
fn_single_line                = true
group_imports                 = "StdExternalCrate"
imports_granularity           = "Module"
match_block_trailing_comma    = true
max_width                     = 150
single_line_if_else_max_width = 100


binop_separator              = "Front"
blank_lines_lower_bound      = 0
blank_lines_upper_bound      = 1
brace_style                  = "SameLineWhere"
color                        = "Auto"
combine_control_expr         = true
comment_width                = 100
condense_wildcard_suffixes   = false
control_brace_style          = "AlwaysSameLine"
edition                      = "2015"
empty_item_single_line       = true
enum_discrim_align_threshold = 0
fn_params_layout             = "Tall"
force_explicit_abi           = true
force_multiline_blocks       = false
format_code_in_doc_comments  = false
format_generated_files       = true
format_macro_bodies          = true
format_macro_matchers        = false
format_strings               = false
hard_tabs                    = false
hex_literal_case             = "Preserve"
imports_indent               = "Block"
imports_layout               = "Mixed"
indent_style                 = "Block"
inline_attribute_width       = 0
match_arm_blocks             = true
match_arm_leading_pipes      = "Never"
merge_derives                = true
newline_style                = "Auto"
normalize_comments           = false
normalize_doc_attributes     = false
remove_nested_parens         = true
reorder_impl_items           = false
reorder_imports              = true
reorder_modules              = true
space_after_colon            = true
space_before_colon           = false
spaces_around_ranges         = false
struct_field_align_threshold = 0
struct_lit_single_line       = true
tab_spaces                   = 4
trailing_comma               = "Vertical"
trailing_semicolon           = true
type_punctuation_density     = "Wide"
use_field_init_shorthand     = false
use_try_shorthand            = false
version                      = "One"
where_single_line            = false
wrap_comments                = false
#required_version = "1.4.38"
disable_all_formatting  = false
emit_mode               = "Files"
error_on_line_overflow  = false
error_on_unformatted    = false
hide_parse_errors       = false
make_backup             = false
overflow_delimited_expr = false
skip_children           = false
unstable_features       = true
