[package]
edition = "2021"
name    = "ocpp_json_validate_attribute"
version = "1.0.0"

[dependencies]
proc-macro2 = "^1.0"
quote       = "^1.0"
syn         = {version = "^2.0", features = ["full"]}
tracing     = "^0.1"

[lib]
proc-macro = true
